- name: Create MySQL databases
  mysql_db:
    name: "{{ item.key.name }}"
    state: "{{ db_state }}"
  loop: "{{ db_dict|dictsort }}"

- name: Create MySQL users and grant priv
  mysql_user:
    name: "{{ item.key.user }}"
    password: "{{ item.key.pass }}"
    priv: '{{ item.key.name }}.*:ALL'
    state: "{{ db_user_state }}"
  loop: "{{ db_dict|dictsort }}"
