- name: Create MySQL databases
  mysql_db:
    name: "{{ item.0.name }}"
    state: "{{ db_state }}"
  loop: "{{ db_dict|subelements('name')|list}}"
 # with_subelements: "{{ db_dict }}"


- name: Create MySQL users and grant priv
  mysql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    priv: '{{ item.name }}.*:ALL'
    state: "{{ db_user_state }}"
  loop: "{{ db_dict|subelements }}"
