- name: Create MySQL databases
  mysql_db:
    name: "{{ item.value.name }}"
    state: "{{ db_state }}"
  loop: "{{ db_dict|list|dictsort }}"

- name: Create MySQL users and grant priv
  mysql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    priv: '{{ item.name }}.*:ALL'
    state: "{{ db_user_state }}"
  loop: "{{ db_dict|list|dictsort }}"
